# Generated by Django 5.0.1 on 2025-10-30 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('barber', models.ForeignKey(limit_choices_to={'is_barber': True}, on_delete=django.db.models.deletion.CASCADE, related_name='offered_services', to=settings.AUTH_USER_MODEL, verbose_name='Barbeiro')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Serviço do Barbeiro',
                'verbose_name_plural': 'Serviços dos Barbeiros',
                'ordering': ['barber__username', 'service__name'],
                'unique_together': {('barber', 'service')},
            },
        ),
    ]
