# Generated by Django 5.0.1 on 2025-10-30 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberOffDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('is_all_day', models.BooleanField(default=True, verbose_name='Dia Todo')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Término')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(limit_choices_to={'is_barber': True}, on_delete=django.db.models.deletion.CASCADE, related_name='off_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Folga do Barbeiro',
                'verbose_name_plural': 'Folgas dos Barbeiros',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='BarberSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Dia da Semana')),
                ('start_time', models.TimeField(verbose_name='Horário de Início')),
                ('end_time', models.TimeField(verbose_name='Horário de Término')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(limit_choices_to={'is_barber': True}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horário do Barbeiro',
                'verbose_name_plural': 'Horários dos Barbeiros',
                'ordering': ['weekday'],
                'unique_together': {('barber', 'weekday')},
            },
        ),
    ]
