# Generated by Django 5.0.1 on 2025-11-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], unique=True, verbose_name='Dia da Semana')),
                ('start_time', models.TimeField(default='09:30', verbose_name='Horário de Início')),
                ('end_time', models.TimeField(default='19:00', verbose_name='Horário de Término')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horário Global da Barbearia',
                'verbose_name_plural': 'Horários Globais da Barbearia',
                'ordering': ['weekday'],
            },
        ),
    ]
